/**
 * Layer 1, the whole engine, as one ES module.
 *
 * `npm run build` bundles this file into the committed `engine/engine.mjs`, and
 * that bundle is the only JavaScript the QML screens import. Nothing here
 * touches the standard library beyond `Math`, `Object`, `String` and `Number`,
 * so the same code runs under Node for the tests and inside a QML engine for
 * play.
 *
 * The reducer is `step(state, input, now) -> { state, events }`.
 */

export const repositoryBootstrap = Object.freeze({
  pluginId: "io.github.dmcchesney.turbo-tables-solo",
  schemaVersion: 1,
});

export {
  createRng,
  cloneRng,
  forkRng,
  hashLabel,
  nextFloat,
  nextInt,
  nextUint32,
  shuffle,
  type Rng,
} from "./rng.ts";

export {
  PRESET_TABLES,
  QUESTIONS_PER_LAP,
  TABLE_MAX,
  TABLE_MIN,
  TABLE_NAMES,
  extraQuestions,
  factAnswer,
  factLabel,
  factLeft,
  factRight,
  lapDeck,
  packFact,
  questionCountForPreset,
  tableFacts,
  tableName,
  tablesForPreset,
  type Fact,
  type PresetId,
} from "./deck.ts";

export {
  FACT_HISTORY_WINDOW,
  cloneFactHistory,
  cloneFactRecord,
  compareByFactHistory,
  factRecordOf,
  newFactRecord,
  orderByFactHistory,
  recentSuccesses,
  recordFactOutcome,
  type FactOutcome,
  type FactRecord,
} from "./history.ts";

export {
  CARDS,
  CARD_SCHEDULE,
  HAND_SIZE,
  QUESTIONS_NEEDED_FLOOR,
  applyFloor,
  cardByBellringerName,
  dealHand,
  isCard,
  type Card,
  type CardDefinition,
  type CardScope,
  type CardTier,
} from "./cards.ts";

export {
  BELLRINGER_STREAK_THRESHOLD,
  CHARGE_GLOW_FROM,
  CHARGE_SEGMENTS,
  STREAK_THRESHOLD,
  chargeReady,
  chargeSegments,
  nextStreak,
  shouldDealHand,
  type StreakEffect,
} from "./streak.ts";

export {
  effectiveProgress,
  positionTriple,
  progressFraction,
  raceLength,
  swapPositions,
  type RacePosition,
} from "./progress.ts";

export {
  PODIUM_SIZE,
  compareRacers,
  headlineForPlace,
  ordinal,
  placeOf,
  positionOrder,
  rankRacers,
  resultsBoard,
  type Headline,
  type Rankable,
  type RankedRacer,
  type ResultsBoard,
} from "./rank.ts";

export {
  EVENT_ORDER,
  SIGNAL_CATALOG,
  isEventOrdered,
  type BlockedEvent,
  type CardUsedEvent,
  type CorrectEvent,
  type FinishedEvent,
  type HandDealtEvent,
  type HitEvent,
  type LapCompleteEvent,
  type PassedByEvent,
  type PassedEvent,
  type PitCrewEvent,
  type RaceEvent,
  type RaceEventType,
  type RevealEvent,
  type Signal,
  type SignalEvent,
  type SwapEvent,
  type WrongEvent,
} from "./events.ts";

export {
  CALLOUT_MS,
  NEXT_FACT_MS,
  REVEAL_MS,
  SETTLE_MS,
  SPUTTER_MS,
  accuracyPercent,
  cloneRacer,
  cloneState,
  createRace,
  currentTable,
  currentTableName,
  factHistoryEntry,
  factHistoryOf,
  humanRacer,
  isStalled,
  raceOrder,
  racerById,
  racerProgress,
  replay,
  step,
  type PitLaneEntry,
  type RaceConfig,
  type RaceInput,
  type RaceMode,
  type RaceState,
  type RaceStatus,
  type Racer,
  type RacerConfig,
  type RacerKind,
  type ScriptedInput,
  type StepResult,
  type UsedCard,
} from "./race.ts";

export {
  ATTACK_CARDS,
  BOOST_CARDS,
  HALF_LAP,
  POLICY_INTERVAL,
  RIVAL_FLOOR_MS,
  RIVAL_LEVELS,
  RIVAL_LEVEL_ORDER,
  RIVAL_ORDER,
  RIVAL_PACE_WINDOW,
  RIVAL_PROFILES,
  RUBBER_BAND_LIMIT,
  aoeVictims,
  childPaceMs,
  chooseTarget,
  choosePlay,
  cloneMind,
  cloneRivals,
  createRivals,
  drawThinkTime,
  drawThinkTimeMs,
  drawWrongAnswer,
  drawsCorrect,
  isAttackCard,
  lastPlaceIds,
  mayAttack,
  mergeSignals,
  mindOf,
  nextRivalDeadline,
  rivalObserve,
  rivalStep,
  rivalTuning,
  rubberBandScale,
  standings,
  victimsOf,
  type PolicyRule,
  type RivalAnswer,
  type RivalConfig,
  type RivalLevel,
  type RivalLevelAdjustment,
  type RivalMind,
  type RivalPersonality,
  type RivalPlay,
  type RivalPlayChoice,
  type RivalProfile,
  type RivalStanding,
  type RivalStepResult,
  type RivalTuning,
  type RivalsState,
} from "./rivals.ts";

export {
  beatsRecord,
  bestRecord,
  cloneRecord,
  cloneTimeline,
  emptyTimeline,
  ghostLead,
  ghostProgressAt,
  ghostReachedAt,
  isCleanMode,
  isRecordEligible,
  recordFromRace,
  recordStep,
  timelineFromEvents,
  updateRecord,
  type GhostSample,
  type GhostTimeline,
  type RecordEntry,
  type RecordUpdate,
} from "./ghost.ts";

export {
  FORBIDDEN_KEY_WORDS,
  KART_BODIES,
  KART_NUMBER_MAX,
  KART_NUMBER_MIN,
  MIGRATIONS,
  PAINT_SWATCHES,
  SAVE_VERSION,
  cloneSave,
  cloneSettings,
  commitRace,
  dateLikeKeys,
  defaultSettings,
  emptySave,
  factHistoryForRace,
  isRecordKey,
  mergeFactHistory,
  migrateSave,
  parseSave,
  raceWasSeededFrom,
  recordKey,
  recordKeyOf,
  recordKeys,
  serialiseSave,
  validateSave,
  withFactHistory,
  type CommitResult,
  type Migration,
  type MigrationResult,
  type SaveFile,
  type SaveIssue,
  type SaveLoad,
  type SaveRecords,
  type SaveSettings,
  type SaveValidation,
} from "./save.ts";
